env:
  browser: true
  commonjs: true
  es6: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
plugins:
  - '@typescript-eslint'
rules: {
  "no-unused-vars": "off",
  "@typescript-eslint/no-unused-vars": "error",
  "import/no-unresolved": "off"
}
